### PR TITLE
feat: Support for JARM

### PR DESCRIPTION
**Pull request by qbert2k**
According to Financial-grade API Security Profile 1.0 - Part 2: Advanced, Section 5.2.2:
The authorization server shall require the response_type value code in conjunction with the response_mode value jwt

Signed-off-by: Javier Rojas Blum <javier.rojas.blum@gmail.com>

### CODE REVIEW

**Comment by qbert2k** [comment]
JARM Brazil OB FAPI Conformance Test failed: fapi1-advanced-final #171

**Comment by ossdhaval** [comment]
> @qbert2k we can workaround this process if you create branch within `JanssenProject:jans-auth-server`, e.g. `javier_171` and open PR based on it, then sonar would not reject scanning (because it's under `JanssenProject` organization) and I can merge it.
> 
> @ossdhaval anyway we need correct status with explanation from sonar

**Comment by yuriyz** [comment]
@qbert2k I see you are updating this PR but we can't merge it because it's opened via fork and sonar can't perform check of such PR. Can you open PR as branch within `JanssenProject:jans-auth-server` (e.g. `javier_171`) ? Not `qbert2k:master`.

**Comment by yuriyz** [comment]
As alternative maybe @ossdhaval can introduce some workaround for such PR.

**Pull request closed without merging**
